CREATE TABLE ciudad (
    id_ciudad NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad),
    CONSTRAINT uq_ciudad_nombre UNIQUE (nombre)
);

CREATE TABLE administrador (
    id_admin NUMBER GENERATED BY DEFAULT AS IDENTITY,
    documento VARCHAR2(30) NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) NOT NULL,
    telefono VARCHAR2(30),

    CONSTRAINT pk_administrador PRIMARY KEY (id_admin),
    CONSTRAINT uq_admin_documento UNIQUE (documento),
    CONSTRAINT uq_admin_correo UNIQUE (correo)
);

CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    documento VARCHAR2(30) NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) NOT NULL,
    telefono VARCHAR2(30),

    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_cliente_documento UNIQUE (documento),
    CONSTRAINT uq_cliente_correo UNIQUE (correo)
);

CREATE TABLE hotel (
    id_hotel NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(200) NOT NULL,
    telefono VARCHAR2(30),
    descripcion VARCHAR2(500),
    id_ciudad NUMBER NOT NULL,
    id_admin NUMBER NOT NULL,

    CONSTRAINT pk_hotel PRIMARY KEY (id_hotel),

    CONSTRAINT fk_hotel_ciudad FOREIGN KEY (id_ciudad)
        REFERENCES ciudad(id_ciudad),

    CONSTRAINT fk_hotel_admin FOREIGN KEY (id_admin)
        REFERENCES administrador(id_admin)
);

CREATE TABLE tipo_habitacion (
    id_tipo NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    capacidad NUMBER NOT NULL,
    costo_temporada_alta NUMBER(12,2) NOT NULL,
    costo_temporada_baja NUMBER(12,2) NOT NULL,
    metros_cuadrados NUMBER(8,2),
    tipo_vista VARCHAR2(30) NOT NULL,
    cantidad_total NUMBER NOT NULL,
    id_hotel NUMBER NOT NULL,

    CONSTRAINT pk_tipo_habitacion PRIMARY KEY (id_tipo),

    CONSTRAINT fk_tipo_hotel FOREIGN KEY (id_hotel)
        REFERENCES hotel(id_hotel),

    CONSTRAINT ck_tipo_capacidad CHECK (capacidad > 0),
    CONSTRAINT ck_tipo_costo_alta CHECK (costo_temporada_alta >= 0),
    CONSTRAINT ck_tipo_costo_baja CHECK (costo_temporada_baja >= 0),
    CONSTRAINT ck_tipo_metros CHECK (metros_cuadrados IS NULL OR metros_cuadrados > 0),
    CONSTRAINT ck_tipo_cantidad CHECK (cantidad_total >= 0),

    CONSTRAINT ck_tipo_vista CHECK (
        tipo_vista IN ('MAR', 'MONUMENTOS', 'PISCINA', 'ESTANDAR')
    )
);

CREATE TABLE habitacion (
    id_habitacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    numero_habitacion NUMBER NOT NULL,
    estado VARCHAR2(30) DEFAULT 'DISPONIBLE' NOT NULL,
    id_hotel NUMBER NOT NULL,
    id_tipo NUMBER NOT NULL,

    CONSTRAINT pk_habitacion PRIMARY KEY (id_habitacion),

    CONSTRAINT fk_habitacion_hotel FOREIGN KEY (id_hotel)
        REFERENCES hotel(id_hotel),

    CONSTRAINT fk_habitacion_tipo FOREIGN KEY (id_tipo)
        REFERENCES tipo_habitacion(id_tipo),

    CONSTRAINT uq_habitacion_hotel_numero UNIQUE (id_hotel, numero_habitacion),

    CONSTRAINT ck_habitacion_estado CHECK (
        estado IN ('DISPONIBLE', 'MANTENIMIENTO', 'INACTIVA')
    )
);

CREATE TABLE servicio (
    id_servicio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(300),
    tipo_costo VARCHAR2(30) NOT NULL,
    aplica_por VARCHAR2(30) NOT NULL,
    precio NUMBER(12,2) NOT NULL,

    CONSTRAINT pk_servicio PRIMARY KEY (id_servicio),

    CONSTRAINT ck_servicio_tipo_costo CHECK (
        tipo_costo IN ('FIJO', 'CONSUMO')
    ),

    CONSTRAINT ck_servicio_aplica_por CHECK (
        aplica_por IN ('RESERVA', 'NOCHE', 'PERSONA')
    ),

    CONSTRAINT ck_servicio_precio CHECK (precio >= 0)
);

CREATE TABLE reserva (
    id_reserva NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    adultos NUMBER NOT NULL,
    menores_3 NUMBER DEFAULT 0 NOT NULL,
    precio_total NUMBER(12,2) NOT NULL,
    codigo_confirmacion VARCHAR2(50) NOT NULL,
    estado VARCHAR2(30) DEFAULT 'ACTIVA' NOT NULL,

    id_hotel NUMBER NOT NULL,
    id_cliente NUMBER NOT NULL,
    id_habitacion NUMBER NOT NULL,

    CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),

    CONSTRAINT fk_reserva_hotel FOREIGN KEY (id_hotel)
        REFERENCES hotel(id_hotel),

    CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente),

    CONSTRAINT fk_reserva_habitacion FOREIGN KEY (id_habitacion)
        REFERENCES habitacion(id_habitacion),

    CONSTRAINT uq_reserva_codigo UNIQUE (codigo_confirmacion),

    CONSTRAINT ck_reserva_fechas CHECK (fecha_salida > fecha_entrada),
    CONSTRAINT ck_reserva_adultos CHECK (adultos >= 1),
    CONSTRAINT ck_reserva_menores CHECK (menores_3 >= 0),
    CONSTRAINT ck_reserva_precio CHECK (precio_total >= 0),

    CONSTRAINT ck_reserva_estado CHECK (
        estado IN ('ACTIVA', 'CANCELADA', 'FINALIZADA')
    )
);

CREATE INDEX idx_hotel_ciudad ON hotel(id_ciudad);
CREATE INDEX idx_hotel_admin ON hotel(id_admin);

CREATE INDEX idx_tipo_hotel ON tipo_habitacion(id_hotel);

CREATE INDEX idx_habitacion_hotel ON habitacion(id_hotel);
CREATE INDEX idx_habitacion_tipo ON habitacion(id_tipo);

CREATE INDEX idx_reserva_hotel ON reserva(id_hotel);
CREATE INDEX idx_reserva_cliente ON reserva(id_cliente);
CREATE INDEX idx_reserva_habitacion ON reserva(id_habitacion);
CREATE INDEX idx_reserva_fechas ON reserva(fecha_entrada, fecha_salida);