CREATE TABLE reserva_servicio (
    id_reserva_servicio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_reserva NUMBER NOT NULL,
    id_servicio NUMBER NOT NULL,
    cantidad NUMBER DEFAULT 1 NOT NULL,

    CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva_servicio),

    CONSTRAINT fk_rs_reserva FOREIGN KEY (id_reserva)
        REFERENCES reserva(id_reserva),

    CONSTRAINT fk_rs_servicio FOREIGN KEY (id_servicio)
        REFERENCES servicio(id_servicio),

    CONSTRAINT ck_rs_cantidad CHECK (cantidad > 0)
);

SELECT ha.id_habitacion,
       ha.numero_habitacion,
       th.nombre AS tipo_habitacion,
       th.capacidad,
       th.tipo_vista,
       th.costo_temporada_alta,
       th.costo_temporada_baja,
       ho.nombre AS hotel,
       c.nombre AS ciudad
FROM habitacion ha
JOIN tipo_habitacion th ON ha.id_tipo = th.id_tipo
JOIN hotel ho ON ha.id_hotel = ho.id_hotel
JOIN ciudad c ON ho.id_ciudad = c.id_ciudad
WHERE ha.id_hotel = :P1_ID_HOTEL
  AND ha.estado = 'DISPONIBLE'
  AND (:P1_CAPACIDAD IS NULL OR th.capacidad >= :P1_CAPACIDAD)
  AND (:P1_TIPO_VISTA IS NULL OR th.tipo_vista = :P1_TIPO_VISTA)
  AND NOT EXISTS (
      SELECT 1
      FROM reserva r
      WHERE r.id_habitacion = ha.id_habitacion
        AND r.estado IN ('ACTIVA', 'FINALIZADA')
        AND r.fecha_entrada < :P1_FECHA_SALIDA
        AND r.fecha_salida > :P1_FECHA_ENTRADA
  );

SELECT TO_CHAR(r.fecha_entrada, 'YYYY-MM') AS periodo,
       c.nombre AS ciudad,
       ho.nombre AS hotel,
       COUNT(r.id_reserva) AS total_reservas
FROM reserva r
JOIN hotel ho ON r.id_hotel = ho.id_hotel
JOIN ciudad c ON ho.id_ciudad = c.id_ciudad
WHERE r.fecha_entrada BETWEEN :P2_FECHA_INICIO AND :P2_FECHA_FIN
  AND (:P2_ID_HOTEL IS NULL OR ho.id_hotel = :P2_ID_HOTEL)
  AND (:P2_ID_CIUDAD IS NULL OR c.id_ciudad = :P2_ID_CIUDAD)
GROUP BY TO_CHAR(r.fecha_entrada, 'YYYY-MM-DD'), c.nombre, ho.nombre
ORDER BY periodo;

CREATE TABLE reserva_servicio (
    id_reserva_servicio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_reserva NUMBER NOT NULL,
    id_servicio NUMBER NOT NULL,
    cantidad NUMBER DEFAULT 1 NOT NULL,

    CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva_servicio),

    CONSTRAINT fk_rs_reserva FOREIGN KEY (id_reserva)
        REFERENCES reserva(id_reserva),

    CONSTRAINT fk_rs_servicio FOREIGN KEY (id_servicio)
        REFERENCES servicio(id_servicio),

    CONSTRAINT ck_rs_cantidad CHECK (cantidad > 0)
);

SELECT ho.nombre AS hotel,
       c.nombre AS ciudad,
       s.nombre AS servicio,
       SUM(rs.cantidad) AS veces_usado
FROM reserva_servicio rs
JOIN reserva r ON rs.id_reserva = r.id_reserva
JOIN servicio s ON rs.id_servicio = s.id_servicio
JOIN hotel ho ON r.id_hotel = ho.id_hotel
JOIN ciudad c ON ho.id_ciudad = c.id_ciudad
WHERE r.fecha_entrada BETWEEN :P5_FECHA_INICIO AND :P5_FECHA_FIN
  AND (:P5_ID_HOTEL IS NULL OR ho.id_hotel = :P5_ID_HOTEL)
  AND (:P5_ID_CIUDAD IS NULL OR c.id_ciudad = :P5_ID_CIUDAD)
  AND r.estado IN ('ACTIVA', 'FINALIZADA')
GROUP BY ho.nombre, c.nombre, s.nombre
ORDER BY veces_usado DESC;